### PR TITLE
Address review issues and improve docs

### LINKED ISSUE #10: Ensure works outside Rails contexts / HTTP name error in Pry
```ruby
[8] pry(main)> Appcanary::Client.vulnerable?
NameError: uninitialized constant Appcanary::HTTP::Bundler
from /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/http.rb:12:in `ship_gemfile'
[9] pry(main)> wtf?
Exception: NameError: uninitialized constant Appcanary::HTTP::Bundler
--
0: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/http.rb:12:in `ship_gemfile'
1: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/assert.rb:28:in `check'
2: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/assert.rb:14:in `vulnerable?'
3: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/assert.rb:42:in `vulnerable?'
4: (pry):14:in `__pry__'
5: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `eval'
6: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
7: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:323:in `handle_line'
8: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
9: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `catch'
[10] pry(main)> Bundler
NameError: uninitialized constant Bundler
```

### PR DESCRIPTION
**Pull request by j0ni**
This closes #10, #11, #12, #14 and #15.

Also, I moved the class methods for the client to the outer namespace as we discussed but didn't make an issue for.

### CODE REVIEW

File: lib/appcanary/configuration.rb [hunk 1]
```diff
@@ -4,18 +4,46 @@ module Appcanary
...
 
     def valid?
-      ! (base_uri.nil? || api_token.nil? || monitor_name.nil?)
+      ! (base_uri.nil? || api_key.nil? || gemfile_lock.nil?)
     end
   end
 
   class ConfigurationError < RuntimeError
+    def initialize(msg)
+      super(msg + <<-FOOTER)
```
Comment (phillmv) [inline lib/appcanary/configuration.rb]: <<-FOOTER)?

maybe define it as a const just before the method?

File: lib/appcanary/configuration.rb [hunk 2]
```diff
@@ -31,27 +59,78 @@ def configure(&block)
...
+            m[:base_uri]     = yaml_config["base_uri"] || APPCANARY_DEFAULT_BASE_URI
           rescue Errno::ENOENT
-            raise ConfigurationError.new("No configuration found")
+            raise ConfigurationError.new("No valid configuration found")
           rescue => e
             raise ConfigurationError.new(e)
           end
+        else
+          raise ConfigurationError.new(
+                  "Bundler is not available and no valid static config exists, can't find Gemfile.lock")
```
Comment (phillmv) [inline lib/appcanary/configuration.rb]: replace with,

"We couldn't find any Gemfile.locks to report on! Don't forget to configure it - consult https://github.com/appcanary/appcanary.rb for more information"

File: lib/appcanary/configuration.rb [hunk 3]
```diff
@@ -4,18 +4,46 @@ module Appcanary
...
+          require "bundler"
+          locate_gemfile_lock
+        rescue LoadError
+          # ignore, handle at resolution time
+          return
+        end
+      end
     end
 
     def valid?
```
Comment (phillmv) [inline lib/appcanary/configuration.rb]: seems like this is checking for whether static conf was provided, and not "validity" per se. Rename?

**Review by phillmv — CHANGES_REQUESTED** [review]

**Comment by phillmv** [comment]
Woops, i may have clicked no the wrong review interface.

File: lib/appcanary/configuration.rb (hunk 1 above)
Comment (j0ni) [reply lib/appcanary/configuration.rb]: I'll change it if you prefer it that way, but the question mark is confusing me. What is it that you dislike about using a heredoc this way?

**Comment by j0ni** [comment]
@phillmv I think it just resulted in you "requesting changes", but I find it pretty confusing myself now.

File: lib/appcanary/configuration.rb (hunk 3 above)
Comment (j0ni) [reply lib/appcanary/configuration.rb]: Fair, I'll think of something. "Sufficient?" perhaps...

File: lib/appcanary/configuration.rb (hunk 1 above)
Comment (phillmv) [reply lib/appcanary/configuration.rb]: we discussed this in person but:

a) I was surprised this was valid syntax!
b) just make it a const :P 
c) it mildly breaks my syntax highlighting ;)

screen shot 2017-01-06 at 10 30 04 am

File: lib/appcanary/configuration.rb [hunk 4]
```diff
@@ -4,18 +4,46 @@ module Appcanary
   APPCANARY_DEFAULT_BASE_URI = "https://appcanary.com/api/v3"
 
   class Configuration
-    attr_accessor :base_uri, :api_token, :monitor_name
+    attr_accessor :base_uri, :api_key, :monitor_name, :gemfile_lock
```
Comment (phillmv) [inline lib/appcanary/configuration.rb]: s/gemfile_lock/gemfile_lock_path/

File: lib/appcanary/configuration.rb [hunk 5]
```diff
@@ -31,27 +59,78 @@ def configure(&block)
...
+    def base_uri=(val);     configuration.base_uri = val;     end
+
+    # throws if config is broken
+    def check_runtime_config!(endpoint, config)
+      if endpoint == :monitors && config[:monitor_name].nil?
+        raise Appcanary::ConfigurationError.new("Appcanary.monitor_name = ???")
+      end
+    end
+
     def resolved_config
```
Comment (phillmv) [inline lib/appcanary/configuration.rb]: 1. By rendering this into a hash that initializes the Client _once_, this means that if you screw up configuration you can't change it later, i.e.

```ruby
Appcanary.api_key = "foo"
Appcanary.vulnerable? # => error
Appcanary.api_key = "correct key"
Appcanary.vulnerable? # => same error
```

this would break my expectations.

Suggestion: just pass in the configuration object! It's messy-mutable-state but so long as _we_ don't mutate it ¯\\\_(ツ)_/¯  

`resolve_config` should check whether config is valid (api_key, gemfile_lock_path); if it's not, try loading in a yaml file then check if it's valid again; then throw corresponding errors

but then it should pass the configuration object down to the client!

Does that make sense?

2. If we're looking for a file, can we use [`Dir.pwd`](http://ruby-doc.org/core-2.4.0/Dir.html#method-c-pwd) instead of Bundle.root? I confess don't know how that works inside a gem but should do the trick. Not that I expect this to run outside of Bundler.

File: lib/appcanary/configuration.rb [hunk 6]
```diff
@@ -4,18 +4,46 @@ module Appcanary
...
+      self.monitor_name = maybe_guess_monitor_name
+      self.gemfile_lock = locate_gemfile_lock
+    end
+
+    def maybe_guess_monitor_name
+      Rails.application.class.parent_name if defined?(Rails)
+    end
+
+    def locate_gemfile_lock
+      if defined?(Bundler)
```
Comment (phillmv) [inline lib/appcanary/configuration.rb]: Suggestion:

```ruby
begin
  require 'bundler'
  if defined?(Bundler)
    return Bundler.default_lockfile
  end
rescue LoadError
end

return nil
```

File: lib/appcanary/http.rb [hunk 7]
```diff
@@ -23,6 +23,8 @@ def ship_gemfile(endpoint, config, &block)
     end
 
     def ship_file(endpoint, payload, config)
+      Appcanary.check_runtime_config!(endpoint, config)
```
Comment (phillmv) [inline lib/appcanary/http.rb]: Let's keep shipfile "dumb" and assume if it gets this far the config is always valid. Perform this check in `update_monitor`? and maybe rename to `valid_monitor_config?`?

File: lib/appcanary/configuration.rb [hunk 8]
```diff
@@ -31,27 +59,78 @@ def configure(&block)
...
+        errors = []
+        errors << "Appcanary.api_key = ???" if m[:api_key].nil?
+        errors << "Appcanary.gemfile_lock = ???" if m[:gemfile_lock].nil?
+        unless errors.empty?
+          raise ConfigurationError.new("Missing configuration:\n\n#{errors.join("\n")}")
+        end
       end
     end
+
+    def vulnerable?(criticality = nil); canary.vulnerable?(criticality); end
```
Comment (phillmv) [inline lib/appcanary/configuration.rb:142]: We discussed in person, but maybe:

`s/vulnerable?/is_this_app_vulnerable?/` or maybe `vulnerable_app?`

and `check` then can take a (to be implemented later) platform, release and path.

**Review by phillmv — CHANGES_REQUESTED** [review]

**Comment by phillmv** [comment]
This is great, btw! Quite liked how much you pulled together in how little time it too you :D

File: lib/appcanary/http.rb [hunk 9]
```diff
@@ -6,10 +6,12 @@ module Appcanary
   class ServiceError < RuntimeError
   end
 
+  # In this module, `config` should always be a hash, typically obtained by
+  # calling `Appcanary::Configuration#resolved`.
   module HTTP
     def ship_gemfile(endpoint, config, &block)
       payload = {
-        file: Bundler.default_lockfile,
+        file: config[:gemfile_lock_path],
```
Comment (j0ni) [inline lib/appcanary/http.rb:14]: lol

**Comment by j0ni** [comment]
OK, I think we're finally on the same page @phillmv, lemme know if not.

Also, this frickin github review UX is weird and I have no idea how to work it. We should have a special tutorial video viewing party or something, because I don't feel qualified to "dismiss review" or even have a clue what the semantics of "dismiss review" are.

File: lib/appcanary/configuration.rb (hunk 5 above)
Comment (j0ni) [reply lib/appcanary/configuration.rb]: Just spotted part 2 of this... I'm inclined to try both. `Dir.pwd` prints the current working directory for the process itself, so it would be contingent on the app within which the gem is being loaded not messing via `Dir.chdir` and the like. 

OTOH, I can't think of a non-bundler context for using this gem which *wouldn't* benefit from a quick look in the current directory for a usable file. Particularly for the yaml config file.

So I'm thinking, start with `Dir.pwd`, fall back to `Bundler.root`, and finally error out.

Not tonight anyway.

Comment (j0ni) [reply lib/appcanary/configuration.rb]: OK @phillmv I did what I said there.

**Comment by j0ni** [comment]
Going to merge this in a little while in the interests of moving along.

File: lib/appcanary/http.rb (hunk 9 above)
Comment (phillmv) [reply lib/appcanary/http.rb:14]: nice

**Review by phillmv — APPROVED** [review]

**Comment by phillmv** [comment]
lgtm
